# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promotion PR

on:
  push:
    branches:
      - dev
      - stage

permissions:
  contents: read
  pull-requests: write

jobs:
  promotion-pr:
    name: Promotion PR
    uses: kirchDev/workflows/.github/workflows/_promotion-pr.yml@1e57db95ff601f03ae87b78e329ef238f9d0cbf6 # v0.8.2
